/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package upapi
// AccountResource Provides information about an Up bank account. 
type AccountResource struct {
	// The unique identifier for this account. 
	Id string `json:"id"`
	// The type of this resource: `accounts`
	Type string `json:"type"`
	Attributes AccountResourceAttributes `json:"attributes"`
	Links AccountResourceLinks `json:"links,omitempty"`
	Relationships AccountResourceRelationships `json:"relationships"`
}
