/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package upapi
import (
	"time"
)
// AccountResourceAttributes struct for AccountResourceAttributes
type AccountResourceAttributes struct {
	// The name associated with the account in the Up application. 
	DisplayName string `json:"displayName"`
	// The bank account type of this account. 
	AccountType AccountTypeEnum `json:"accountType"`
	// The available balance of the account, taking into account any amounts that are currently on hold. 
	Balance MoneyObject `json:"balance"`
	// The date-time at which this account was first opened. 
	CreatedAt time.Time `json:"createdAt"`
}
