/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package upapi
// WebhookDeliveryStatusEnum Specifies the nature of the success or failure of a webhook delivery attempt to the subscribed webhook URL. The currently returned values are described below:  - **`DELIVERED`**: The event was delivered to the webhook URL   successfully and a `200` response was received. - **`UNDELIVERABLE`**: The webhook URL was not reachable, or timed out. - **`BAD_RESPONSE_CODE`**: The event was delivered to the webhook URL   but a non-`200` response was received. 
type WebhookDeliveryStatusEnum string

// List of WebhookDeliveryStatusEnum
const (
	DELIVERED WebhookDeliveryStatusEnum = "DELIVERED"
	UNDELIVERABLE WebhookDeliveryStatusEnum = "UNDELIVERABLE"
	BAD_RESPONSE_CODE WebhookDeliveryStatusEnum = "BAD_RESPONSE_CODE"
)
