/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package upapi
// WebhookEventTypeEnum Specifies the type of a webhook event. This can be used to determine what action to take in response to the event, such as which relationships to expect. 
type WebhookEventTypeEnum string

// List of WebhookEventTypeEnum
const (
	TRANSACTION_CREATED WebhookEventTypeEnum = "TRANSACTION_CREATED"
	TRANSACTION_SETTLED WebhookEventTypeEnum = "TRANSACTION_SETTLED"
	TRANSACTION_DELETED WebhookEventTypeEnum = "TRANSACTION_DELETED"
	PING WebhookEventTypeEnum = "PING"
)
