/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package upapi
// ListWebhooksResponse Successful response to get all webhooks. This returns a paginated list of webhooks, which can be scrolled by following the `prev` and `next` links if present. 
type ListWebhooksResponse struct {
	// The list of webhooks returned in this response. 
	Data []WebhookResource `json:"data"`
	Links ListAccountsResponseLinks `json:"links"`
}
