/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package upapi
// HoldInfoObject Provides information about the amount at which a transaction was in the `HELD` status. 
type HoldInfoObject struct {
	// The amount of this transaction while in the `HELD` status, in Australian dollars. 
	Amount MoneyObject `json:"amount"`
	// The foreign currency amount of this transaction while in the `HELD` status. This field will be `null` for domestic transactions. The amount was converted to the AUD amount reflected in the `amount` field. 
	ForeignAmount *MoneyObject `json:"foreignAmount"`
}
