/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package upapi
import (
	"time"
)
// WebhookEventResourceAttributes struct for WebhookEventResourceAttributes
type WebhookEventResourceAttributes struct {
	// The type of this event. This can be used to determine what action to take in response to the event. 
	EventType WebhookEventTypeEnum `json:"eventType"`
	// The date-time at which this event was generated. 
	CreatedAt time.Time `json:"createdAt"`
}
