/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package upapi
// RoundUpObject Provides information about how a Round Up was applied, such as whether or not a boost was included in the Round Up. 
type RoundUpObject struct {
	// The total amount of this Round Up, represented as negative value. 
	Amount MoneyObject `json:"amount"`
	// The portion of the Round Up `amount` owing to boosted Round Ups, represented as a negative value. If no boost was added to the Round Up this field will be `null`. 
	BoostPortion *MoneyObject `json:"boostPortion"`
}
