/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package upapi
// WebhookDeliveryLogResource Provides historical webhook event delivery information for analysis and debugging purposes. 
type WebhookDeliveryLogResource struct {
	// The unique identifier for this log entry. 
	Id string `json:"id"`
	// The type of this resource: `webhook-delivery-logs`
	Type string `json:"type"`
	Attributes WebhookDeliveryLogResourceAttributes `json:"attributes"`
	Links AccountResourceLinks `json:"links,omitempty"`
	Relationships WebhookDeliveryLogResourceRelationships `json:"relationships"`
}
