/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package upapi
// ErrorObjectSource If applicable, location in the request that this error relates to. This may be a parameter in the query string, or a an attribute in the request body. 
type ErrorObjectSource struct {
	// If this error relates to a query parameter, the name of the parameter. 
	Parameter string `json:"parameter,omitempty"`
	// If this error relates to an attribute in the request body, a rfc-6901 JSON pointer to the attribute. 
	Pointer string `json:"pointer,omitempty"`
}
