/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package upapi
// AccountTypeEnum Specifies the type of bank account. Currently returned values are `SAVER` and `TRANSACTIONAL`.
type AccountTypeEnum string

// List of AccountTypeEnum
const (
	SAVER AccountTypeEnum = "SAVER"
	TRANSACTIONAL AccountTypeEnum = "TRANSACTIONAL"
)
