/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package upapi
// ErrorObject Provides information about an error processing a request. 
type ErrorObject struct {
	// The HTTP status code associated with this error. This can also be obtained from the response headers. The status indicates the broad type of error according to HTTP semantics. 
	Status string `json:"status"`
	// A short description of this error. This should be stable across multiple occurrences of this type of error and typically expands on the reason for the status code. 
	Title string `json:"title"`
	// A detailed description of this error. This should be considered unique to individual occurrences of an error and subject to change. It is useful for debugging purposes. 
	Detail string `json:"detail"`
	Source ErrorObjectSource `json:"source,omitempty"`
}
