/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package upapi
// ListAccountsResponseLinks struct for ListAccountsResponseLinks
type ListAccountsResponseLinks struct {
	// The link to the previous page in the results. If this value is `null` there is no previous page. 
	Prev *string `json:"prev"`
	// The link to the next page in the results. If this value is `null` there is no next page. 
	Next *string `json:"next"`
}
